### ISSUE TITLE
Could not resolve valid mod collection

### ISSUE THREAD

**Issue by waidesoper** [skyrising/skyblock#1]
I've spun up a MultiMC instance with QuickCarpet and skyblock mods and when I try to launch the instance I get the following error:
```
Mods:
  [✔️] quickcarpet-2.0.0-dev.20190830.115222
  [✔️] skyblock-fc-1.14.4-1.0.0

Params:
  --username  --version MultiMC5 --gameDir /home/waide/.local/share/multimc/instances/Skyblock 1.14/.minecraft --assetsDir /home/waide/.local/share/multimc/assets --assetIndex 1.14 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx6128m, -Duser.language=en]


Minecraft process ID: 14841


Using onesix launcher.

[08:20:24] [main/INFO]: Loading for game Minecraft 1.14.4
[08:20:24] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:159)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:122)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: skyblock requires {carpet @ [*]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:157)
	... 10 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)
	... 12 more
Exiting with -1
Process exited with code 255.
```

I've tried this on multiple computers, and in the vanilla Minecraft launcher all with the same results.

**Comment by skyrising** [comment]
Your using the fc version of skyblock (which needs fabric-carpet).
Use the other version of skyblock for quickcarpet
