### ISSUE TITLE
World crashes on startup

### ISSUE THREAD

**Issue by anonaddict** [skyrising/skyblock#42]
[15:31:16] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[15:31:16] [main/INFO]: Loading 8 mods:
	- fabric-resource-loader-v0 0.4.17+801ec85b60 via quickcarpet
	- fabricloader 0.13.3
	- java 17
	- malilib 0.11.5
	- minecraft 1.18.2
	- quickcarpet 3.4.0-dev.50+gfb2d2fe
	- quickcarpet-api 1.1.0 via quickcarpet
	- skyblock 3.2.1
[15:31:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/user/.config/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:31:16] [main/INFO]: Compatibility level set to JAVA_16
[15:31:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:31:30] [Render thread/INFO]: Setting user: Addict_c
[15:31:30] [Render thread/INFO]: Quick Carpet module skyblock version 3.2.1 registered
[15:31:31] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[15:31:32] [Render thread/INFO]: Narrator library successfully loaded
[15:31:32] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Resource Loader (v0), Fabric Loader, MaLiLib, QuickCarpet, QuickCarpet API, SkyBlock)
[15:31:33] [Render thread/INFO]: Parsing settings for module skyblock from class skyblock.SkyBlockSettings
[15:31:33] [Render thread/WARN]: Deprecated: making private skyblock.SkyBlockSettings$WanderingTraderSkyblockTradesChange() accessible, please use a public constructor instead
[15:31:33] [Render thread/INFO]: Quick Carpet module skyblock version 3.2.1 initialized
[15:31:36] [Render thread/INFO]: OpenAL initialized on device Built-in Audio Analog Stereo
[15:31:36] [Render thread/INFO]: Sound engine started
[15:31:36] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[15:31:37] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[15:31:37] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[15:31:37] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[15:31:37] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[15:31:37] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[15:31:37] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[15:31:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[15:31:38] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[15:31:38] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[15:31:52] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:31:52] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:31:52] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:31:52] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[15:31:52] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:31:52] [Render thread/INFO]: Loaded 7 recipes
[15:31:52] [Render thread/INFO]: Loaded 1141 advancements
[15:31:54] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:31:54] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[15:31:54] [Server thread/INFO]: Generating keypair
[15:32:06] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception initializing level
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:395) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3823(class_1132.java:70) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.longs.LongSet net.minecraft.class_2839.method_12180(net.minecraft.class_3195)'
	at skyblock.SkyBlockUtils.processStronghold(SkyBlockUtils.java:60) ~[skyblock-3.2.1.jar:?]
	at skyblock.SkyBlockUtils.deleteBlocks(SkyBlockUtils.java:55) ~[skyblock-3.2.1.jar:?]
	at net.minecraft.class_2806.handler$zik000$onLighting(class_2806.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20614(class_2806.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:289) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:649) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:643) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[15:32:06] [Server thread/ERROR]: This crash report has been saved to: /home/user/.config/gdlauncher_next/instances/cursed/crash-reports/crash-2022-04-16_15.32.06-server.txt
[15:32:06] [Server thread/INFO]: Stopping server
[15:32:06] [Server thread/INFO]: Saving players
[15:32:06] [Server thread/INFO]: Saving worlds
[15:32:06] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.longs.LongSet net.minecraft.class_2839.method_12180(net.minecraft.class_3195)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'it.unimi.dsi.fastutil.longs.LongSet net.minecraft.class_2839.method_12180(net.minecraft.class_3195)'
	at skyblock.SkyBlockUtils.processStronghold(SkyBlockUtils.java:60) ~[skyblock-3.2.1.jar:?]
	at skyblock.SkyBlockUtils.deleteBlocks(SkyBlockUtils.java:55) ~[skyblock-3.2.1.jar:?]
	at net.minecraft.class_2806.handler$zik000$onLighting(class_2806.java:529) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_20614(class_2806.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:289) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:649) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:643) ~[client-intermediary.jar:?]
	... 12 more

**Comment by skyrising** [comment]
At the moment this mod is not updated for 1.18.2 yet.

**Comment by skyrising** [comment]
Update is now ready: https://github.com/skyrising/skyblock/releases/tag/v3.2.3
